// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoTopdown.Infrastructure.Persistence;

#nullable disable

namespace ProjetoTopdown.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoTopdown.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "111.111.111-11",
                            Email = "cliente1@email.com",
                            Name = "Cliente de Teste 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "222.222.222-22",
                            Email = "cliente2@email.com",
                            Name = "Cliente de Teste 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "333.333.333-33",
                            Email = "cliente3@email.com",
                            Name = "Cliente de Teste 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "444.444.444-44",
                            Email = "cliente4@email.com",
                            Name = "Cliente de Teste 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "555.555.555-55",
                            Email = "cliente5@email.com",
                            Name = "Cliente de Teste 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "666.666.666-66",
                            Email = "cliente6@email.com",
                            Name = "Cliente de Teste 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "777.777.777-77",
                            Email = "cliente7@email.com",
                            Name = "Cliente de Teste 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "888.888.888-88",
                            Email = "cliente8@email.com",
                            Name = "Cliente de Teste 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "999.999.999-99",
                            Email = "cliente9@email.com",
                            Name = "Cliente de Teste 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "101010.101010.101010-1010",
                            Email = "cliente10@email.com",
                            Name = "Cliente de Teste 10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "111111.111111.111111-1111",
                            Email = "cliente11@email.com",
                            Name = "Cliente de Teste 11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "121212.121212.121212-1212",
                            Email = "cliente12@email.com",
                            Name = "Cliente de Teste 12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "131313.131313.131313-1313",
                            Email = "cliente13@email.com",
                            Name = "Cliente de Teste 13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "141414.141414.141414-1414",
                            Email = "cliente14@email.com",
                            Name = "Cliente de Teste 14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "151515.151515.151515-1515",
                            Email = "cliente15@email.com",
                            Name = "Cliente de Teste 15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "161616.161616.161616-1616",
                            Email = "cliente16@email.com",
                            Name = "Cliente de Teste 16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "171717.171717.171717-1717",
                            Email = "cliente17@email.com",
                            Name = "Cliente de Teste 17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "181818.181818.181818-1818",
                            Email = "cliente18@email.com",
                            Name = "Cliente de Teste 18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "191919.191919.191919-1919",
                            Email = "cliente19@email.com",
                            Name = "Cliente de Teste 19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Document = "202020.202020.202020-2020",
                            Email = "cliente20@email.com",
                            Name = "Cliente de Teste 20"
                        });
                });

            modelBuilder.Entity("ProjetoTopdown.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ProjetoTopdown.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProjetoTopdown.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 1",
                            Price = 30.5m,
                            Sku = "SKU-1001",
                            StockQty = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 2",
                            Price = 41m,
                            Sku = "SKU-1002",
                            StockQty = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 3",
                            Price = 51.5m,
                            Sku = "SKU-1003",
                            StockQty = 15
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 4",
                            Price = 62m,
                            Sku = "SKU-1004",
                            StockQty = 20
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 5",
                            Price = 72.5m,
                            Sku = "SKU-1005",
                            StockQty = 25
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 6",
                            Price = 83m,
                            Sku = "SKU-1006",
                            StockQty = 30
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 7",
                            Price = 93.5m,
                            Sku = "SKU-1007",
                            StockQty = 35
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 8",
                            Price = 104m,
                            Sku = "SKU-1008",
                            StockQty = 40
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 9",
                            Price = 114.5m,
                            Sku = "SKU-1009",
                            StockQty = 45
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 10",
                            Price = 125m,
                            Sku = "SKU-1010",
                            StockQty = 50
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 11",
                            Price = 135.5m,
                            Sku = "SKU-1011",
                            StockQty = 55
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 12",
                            Price = 146m,
                            Sku = "SKU-1012",
                            StockQty = 60
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 13",
                            Price = 156.5m,
                            Sku = "SKU-1013",
                            StockQty = 65
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 14",
                            Price = 167m,
                            Sku = "SKU-1014",
                            StockQty = 70
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 15",
                            Price = 177.5m,
                            Sku = "SKU-1015",
                            StockQty = 75
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 16",
                            Price = 188m,
                            Sku = "SKU-1016",
                            StockQty = 80
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 17",
                            Price = 198.5m,
                            Sku = "SKU-1017",
                            StockQty = 85
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 18",
                            Price = 209m,
                            Sku = "SKU-1018",
                            StockQty = 90
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 19",
                            Price = 219.5m,
                            Sku = "SKU-1019",
                            StockQty = 95
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 20",
                            Price = 230m,
                            Sku = "SKU-1020",
                            StockQty = 100
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 21",
                            Price = 240.5m,
                            Sku = "SKU-1021",
                            StockQty = 105
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 22",
                            Price = 251m,
                            Sku = "SKU-1022",
                            StockQty = 110
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 23",
                            Price = 261.5m,
                            Sku = "SKU-1023",
                            StockQty = 115
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 24",
                            Price = 272m,
                            Sku = "SKU-1024",
                            StockQty = 120
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 25",
                            Price = 282.5m,
                            Sku = "SKU-1025",
                            StockQty = 125
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 26",
                            Price = 293m,
                            Sku = "SKU-1026",
                            StockQty = 130
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 27",
                            Price = 303.5m,
                            Sku = "SKU-1027",
                            StockQty = 135
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 28",
                            Price = 314m,
                            Sku = "SKU-1028",
                            StockQty = 140
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 29",
                            Price = 324.5m,
                            Sku = "SKU-1029",
                            StockQty = 145
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 30",
                            Price = 335m,
                            Sku = "SKU-1030",
                            StockQty = 150
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 31",
                            Price = 345.5m,
                            Sku = "SKU-1031",
                            StockQty = 155
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 32",
                            Price = 356m,
                            Sku = "SKU-1032",
                            StockQty = 160
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 33",
                            Price = 366.5m,
                            Sku = "SKU-1033",
                            StockQty = 165
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 34",
                            Price = 377m,
                            Sku = "SKU-1034",
                            StockQty = 170
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 35",
                            Price = 387.5m,
                            Sku = "SKU-1035",
                            StockQty = 175
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 36",
                            Price = 398m,
                            Sku = "SKU-1036",
                            StockQty = 180
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 37",
                            Price = 408.5m,
                            Sku = "SKU-1037",
                            StockQty = 185
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 38",
                            Price = 419m,
                            Sku = "SKU-1038",
                            StockQty = 190
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 39",
                            Price = 429.5m,
                            Sku = "SKU-1039",
                            StockQty = 195
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 40",
                            Price = 440m,
                            Sku = "SKU-1040",
                            StockQty = 200
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 41",
                            Price = 450.5m,
                            Sku = "SKU-1041",
                            StockQty = 205
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 42",
                            Price = 461m,
                            Sku = "SKU-1042",
                            StockQty = 210
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 43",
                            Price = 471.5m,
                            Sku = "SKU-1043",
                            StockQty = 215
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 44",
                            Price = 482m,
                            Sku = "SKU-1044",
                            StockQty = 220
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 45",
                            Price = 492.5m,
                            Sku = "SKU-1045",
                            StockQty = 225
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 46",
                            Price = 503m,
                            Sku = "SKU-1046",
                            StockQty = 230
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 47",
                            Price = 513.5m,
                            Sku = "SKU-1047",
                            StockQty = 235
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 48",
                            Price = 524m,
                            Sku = "SKU-1048",
                            StockQty = 240
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 49",
                            Price = 534.5m,
                            Sku = "SKU-1049",
                            StockQty = 245
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Produto de Teste 50",
                            Price = 545m,
                            Sku = "SKU-1050",
                            StockQty = 250
                        });
                });

            modelBuilder.Entity("ProjetoTopdown.Domain.Entities.Order", b =>
                {
                    b.HasOne("ProjetoTopdown.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjetoTopdown.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ProjetoTopdown.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoTopdown.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProjetoTopdown.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
